//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System.Data.EntityClient;
using System.Data.Objects;
using DataAccess.NorthwindEntitiesMockObjectSet;

namespace DataAccess
{
    /// <summary>
    /// The concrete mock context object that implements the context's interface.
    /// Provide an instance of this mock context class to client logic when testing, 
    /// instead of providing a functional context object.
    /// </summary>
    public partial class NorthwindEntitiesMock : INorthwindEntities
    {
        public IObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = new MockObjectSet<Category>()); }
        }
        private IObjectSet<Category> _categories;
        public IObjectSet<Product> Products
        {
            get { return _products  ?? (_products = new MockObjectSet<Product>()); }
        }
        private IObjectSet<Product> _products;
    
    	public void Reset()
    	{
    		((MockObjectSet<Category>)Categories).ClearAll();
    		((MockObjectSet<Product>)Products).ClearAll();
    	}
    
    
    }
}
